sudo: false
dist: trusty
language: generic

env:
  global:
    - GCC=gcc-5
    - GXX=g++-5

cache:
  directories:
    - $HOME/.stack/

addons:
  apt:
    packages:
      - gcc-5
      - g++-5
      - libgmp-dev
      - llvm-5.0-dev
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export CC=/usr/bin/$GCC
  - export CXX=/usr/bin/$GXX

install:
  - stack update
  - travis_wait 120 stack --no-terminal --install-ghc test --only-dependencies
  - stack build --coverage
  - stack install

script:
  - mkdir output
  - stack exec grin -- grin/grin/sum_simple.grin
  - stack exec idris -- frontend-test/idris/Hello.idr -i frontend-test/idris --codegen grin -o hello.grin
  - stack --no-terminal test --coverage
